#!/usr/bin/env bash
# Install the 15-minute background ring sync as a Windows Scheduled Task.
# Generates sync_task.vbs (hidden-window wrapper) with THIS repo's absolute
# path, then registers/updates the "RingLocalSync" task. Re-run after moving
# the repo. Requires Git Bash.
set -e
cd "$(dirname "$0")"

HERE_UNIX="$(pwd)"
HERE_WIN="$(cygpath -w "$HERE_UNIX")"
BASH_WIN="$(cygpath -w "$(command -v bash)")"

cat > sync_task.vbs << EOF
' AUTO-GENERATED by install_task.sh — do not edit; re-run installer instead.
Set sh = CreateObject("WScript.Shell")
sh.Run """${BASH_WIN}"" -lc ""${HERE_UNIX}/sync_dashboard.sh >> ${HERE_UNIX}/sync.log 2>&1""", 0, False
EOF

MSYS_NO_PATHCONV=1 schtasks /Create /TN "RingLocalSync" /SC MINUTE /MO 15 \
    /TR "wscript.exe \"${HERE_WIN}\\sync_task.vbs\"" /F
echo "Installed: RingLocalSync (every 15 min) -> ${HERE_WIN}\\sync_task.vbs"
